using System;
using System.Collections.Generic;
using UnityEngine;

public class UnityMainThreadDispatcher : MonoBehaviour
{
    private static readonly Queue<Action> _executionQueue = new Queue<Action>();
    private static UnityMainThreadDispatcher _instance = null;

    public static bool Exists() => _instance != null;

    public static UnityMainThreadDispatcher Instance()
    {
        if (!Exists())
            throw new Exception("UnityMainThreadDispatcher nÃ£o existe na cena. Adicione este script em algum GameObject.");
        return _instance;
    }

    void Awake()
    {
        if (_instance == null)
        {
            _instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
        }
    }

    void Update()
    {
        lock (_executionQueue)
        {
            while (_executionQueue.Count > 0)
            {
                _executionQueue.Dequeue().Invoke();
            }
        }
    }

    public void Enqueue(Action action)
    {
        if (action == null)
            throw new ArgumentNullException("action");
        lock (_executionQueue)
        {
            _executionQueue.Enqueue(action);
        }
    }
}